"""Create database

Revision ID: 5686743a2b2e
Revises: 
Create Date: 2023-12-17 19:47:19.372584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5686743a2b2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_title', sa.String(length=100), nullable=False),
    sa.Column('album_title', sa.String(length=100), nullable=False),
    sa.Column('music_producer', sa.String(length=20), nullable=True),
    sa.Column('singer', sa.String(length=20), nullable=True),
    sa.Column('lyricist', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('lyrics', sa.String(length=500), nullable=True),
    sa.Column('audiofile', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('playlist_songs',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_songs')
    op.drop_table('user')
    op.drop_table('song')
    op.drop_table('playlist')
    # ### end Alembic commands ###
